resolver: lts-16.14

extra-deps:
  # - git: https://github.com/juhp/hsbugzilla.git
  #  commit: b3cc51c12c4c5925f07d8bb0abf9047ef5842bf6
  - bugzilla-redhat-0.3.0@rev:1
  - git: https://github.com/juhp/fedora-dists.git
    commit: a4f6f690e50c6c2e69cc81afb13b7e4581079907
  - git: https://github.com/juhp/bodhi-hs.git
    commit: c7d8f0728e7e34ec872755f1081dca1e32fa2f80
  - git: https://github.com/juhp/pagure-hs.git
    commit: 5ad5f162fb60e8cba72d7cde0257496bbb309481
  - git: https://github.com/juhp/koji-hs.git
    commit: 6c51d1bcc64d40bd4d7d1a3dab19ddebcb2a61cd
  - rpmbuild-order-0.4.2
  # - git: https://github.com/juhp/rpmbuild-order.git
  #   commit: c05a0ab10e13ff258bff37eae017f896e7369460
  # in lts16:
  - pretty-terminal-0.1.0.0
  - git: https://github.com/juhp/copr-hs.git
    commit: ba98747c810893212fa057fdcd8aa72a6c38137f
  # - git: https://github.com/juhp/http-query.git
  #   commit: 95bfbbfde4c1ea1862fc4ed03bd5f0635253486e
  - http-query-0.1.0
  - git: https://github.com/juhp/pdc-hs.git
    commit: d7e59cedf72f4253b10b1c723dd0b9e27fa11688
