resolver: lts-15.16

extra-deps:
  - git: https://github.com/juhp/hsbugzilla.git
    commit: bd4d90d3696e079fd095b75e23e7a4429635e93a
  - git: https://github.com/juhp/fedora-dists.git
    commit: c6d51f56869065505fc0b8ee453246dd2bb5252f
  - git: https://github.com/juhp/bodhi-hs.git
    commit: 279a37b91aa15a54aeda1daa0ad79e4da71c0874
  - git: https://github.com/juhp/pagure-hs.git
    commit: 813010d6c1377232476f48321cd48808e0b356f2
  - git: https://github.com/juhp/koji-hs.git
    commit: 84873619d266d31b4be2c1dc6eb24c0128e389dc
  - rpmbuild-order-0.4.1
  - pretty-terminal-0.1.0.0
