resolver: lts-14.27

extra-deps:
  - git: https://github.com/juhp/hsbugzilla.git
    commit: ae1fa7be0e3480c6979fc04f232cc09c16e4cb7d
  - git: https://github.com/juhp/fedora-dists.git
    commit: 361ca6f8dba14e561d4725a1cc00185971c1e52c
  - simple-cmd-args-0.1.6
  - git: https://github.com/juhp/bodhi-hs.git
    commit: f80aa0c1f279be63aff535a8ec600b3fb3cc6113
  - git: https://github.com/juhp/pagure-hs.git
    commit: 63c3f77935ae8100373a05c9467f6a776d7e454e
  - git: https://github.com/juhp/koji-hs.git
    commit: 9ff1fe697c3d007e23373b4a5d8169bcc18e3e53
