resolver: lts-15.16

extra-deps:
  # - git: https://github.com/juhp/hsbugzilla.git
  #  commit: b3cc51c12c4c5925f07d8bb0abf9047ef5842bf6
  - bugzilla-redhat-0.3.0
  - git: https://github.com/juhp/fedora-dists.git
    commit: c6d51f56869065505fc0b8ee453246dd2bb5252f
  - git: https://github.com/juhp/bodhi-hs.git
    commit: 279a37b91aa15a54aeda1daa0ad79e4da71c0874
  - git: https://github.com/juhp/pagure-hs.git
    commit: 813010d6c1377232476f48321cd48808e0b356f2
  - git: https://github.com/juhp/koji-hs.git
    commit: 84873619d266d31b4be2c1dc6eb24c0128e389dc
  - rpmbuild-order-0.4.2
  - pretty-terminal-0.1.0.0
  # - git: https://github.com/juhp/rpmbuild-order.git
  #   commit: c05a0ab10e13ff258bff37eae017f896e7369460
  - git: https://github.com/juhp/copr-hs.git
    commit: fa3d1b7f0550f88c82b025fe46300a8a9cb50275
