name: CI build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10', '8.8', '8.6']
    name: Haskell GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          cabal-version: '3.2'
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('*/*.cabal') }}-${{ hashFiles('*/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-
      - run: cabal v2-update
      - run: cabal v2-build
      - run: cabal v2-sdist
